In [2]:
# Load the CSV file to inspect its contents and pick out the top 5 countries based on growth percentage
import pandas as pd
file_path_csv = '/workspaces/placement-training/Python/EDA/data/uk_commodities.csv'

# Read the CSV file
df_filtered = pd.read_csv(file_path_csv)

df_filtered['%Growth'] = pd.to_numeric(df_filtered['%Growth'], errors='coerce')

# Step 1: Exclude rows with negative %Growth values
df_filtered = df_filtered[df_filtered['%Growth'] >= 0]

# Step 2: Calculate the mean of the '2022-2023' column
mean_2022_2023 = df_filtered['2022-2023'].mean()

# Step 3: Filter rows where '2022-2023' is greater than or equal to the mean
df_filtered = df_filtered[df_filtered['2022-2023'] >= mean_2022_2023]

# Step 4: Sort the remaining data by %Growth in descending order
df_sorted = df_filtered.sort_values(by='%Growth', ascending=False)

# Display the resulting dataframe
df_sorted.head()

,S.No.,HSCode,Commodity,2022-2023,2023-2024,%Growth
45,46,48,"PAPER AND PAPERBOARD; ARTICLES OF PAPER PULP, ...",118618.83,223369.61,88.31
69,70,72,IRON AND STEEL,176926.28,317390.26,79.39
7,8,10,CEREALS.,126492.91,194709.47,53.93
24,25,27,"MINERAL FUELS, MINERAL OILS AND PRODUCTS OF TH...",749695.55,1103646.19,47.21
83,84,87,VEHICLES OTHER THAN RAILWAY OR TRAMWAY ROLLING...,176916.30,236882.19,33.90